# Stubs for http.client (Python 3.4)

from typing import Undefined, Any, Dict
import email.message
import io

responses = Undefined(Dict[int, str])

class HTTPMessage(email.message.Message):
    def getallmatchingheaders(self, name): ...

class HTTPResponse(io.RawIOBase):
    fp = Undefined(Any)
    debuglevel = Undefined(Any)
    headers = Undefined(Any)
    version = Undefined(Any)
    status = Undefined(Any)
    reason = Undefined(Any)
    chunked = Undefined(Any)
    chunk_left = Undefined(Any)
    length = Undefined(Any)
    will_close = Undefined(Any)
    def __init__(self, sock, debuglevel=0, method=None, url=None): ...
    code = Undefined(Any)
    def begin(self): ...
    def close(self): ...
    def flush(self): ...
    def readable(self): ...
    def isclosed(self): ...
    def read(self, amt=None): ...
    def readinto(self, b): ...
    def fileno(self): ...
    def getheader(self, name, default=None): ...
    def getheaders(self): ...
    def __iter__(self): ...
    def info(self): ...
    def geturl(self): ...
    def getcode(self): ...

class HTTPConnection:
    response_class = Undefined(Any)
    default_port = Undefined(Any)
    auto_open = Undefined(Any)
    debuglevel = Undefined(Any)
    mss = Undefined(Any)
    timeout = Undefined(Any)
    source_address = Undefined(Any)
    sock = Undefined(Any)
    def __init__(self, host, port=None, timeout=Undefined, source_address=None): ...
    def set_tunnel(self, host, port=None, headers=None): ...
    def set_debuglevel(self, level): ...
    def connect(self): ...
    def close(self): ...
    def send(self, data): ...
    def putrequest(self, method, url, skip_host=0, skip_accept_encoding=0): ...
    def putheader(self, header, *values): ...
    def endheaders(self, message_body=None): ...
    def request(self, method, url, body=None, headers=Undefined): ...
    def getresponse(self): ...

class HTTPSConnection(HTTPConnection):
    default_port = Undefined(Any)
    key_file = Undefined(Any)
    cert_file = Undefined(Any)
    def __init__(self, host, port=None, key_file=None, cert_file=None, timeout=Undefined,
                 source_address=None, *, context=None, check_hostname=None): ...
    sock = Undefined(Any)
    def connect(self): ...

class HTTPException(Exception): ...
class NotConnected(HTTPException): ...
class InvalidURL(HTTPException): ...

class UnknownProtocol(HTTPException):
    args = Undefined(Any)
    version = Undefined(Any)
    def __init__(self, version): ...

class UnknownTransferEncoding(HTTPException): ...
class UnimplementedFileMode(HTTPException): ...

class IncompleteRead(HTTPException):
    args = Undefined(Any)
    partial = Undefined(Any)
    expected = Undefined(Any)
    def __init__(self, partial, expected=None): ...

class ImproperConnectionState(HTTPException): ...
class CannotSendRequest(ImproperConnectionState): ...
class CannotSendHeader(ImproperConnectionState): ...
class ResponseNotReady(ImproperConnectionState): ...

class BadStatusLine(HTTPException):
    args = Undefined(Any)
    line = Undefined(Any)
    def __init__(self, line): ...

class LineTooLong(HTTPException):
    def __init__(self, line_type): ...

error = HTTPException
