# Stubs for typing (Python 2.7)

from abc import abstractmethod, ABCMeta

# Definitions of special type checking related constructs.  Their definition
# are not used, so their value does not matter.

cast = object()
overload = object()
Undefined = object()
Any = object()
TypeVar = object()
Generic = object()
Tuple = object()
Callable = object()
builtinclass = object()
_promote = object()
NamedTuple = object()

# Type aliases

class TypeAlias:
    # Class for defining generic aliases for library types.
    def __init__(self, target_type): ...
    def __getitem__(self, typeargs): ...

Union = TypeAlias(object)
Optional = TypeAlias(object)
List = TypeAlias(object)
Dict = TypeAlias(object)
Set = TypeAlias(object)

# Predefined type variables.
AnyStr = TypeVar('AnyStr', str, unicode)

# Abstract base classes.

_T = TypeVar('_T')
_KT = TypeVar('_KT')
_VT = TypeVar('_VT')

# TODO Container etc.

class SupportsInt(metaclass=ABCMeta):
    @abstractmethod
    def __int__(self) -> int: ...

class SupportsFloat(metaclass=ABCMeta):
    @abstractmethod
    def __float__(self) -> float: ...

class SupportsAbs(Generic[_T]):
    @abstractmethod
    def __abs__(self) -> _T: ...

class SupportsRound(Generic[_T]):
    @abstractmethod
    def __round__(self, ndigits: int = 0) -> _T: ...

class Reversible(Generic[_T]):
    @abstractmethod
    def __reversed__(self) -> Iterator[_T]: ...

class Sized(metaclass=ABCMeta):
    @abstractmethod
    def __len__(self) -> int: ...

class Iterable(Generic[_T]):
    @abstractmethod
    def __iter__(self) -> Iterator[_T]: ...

class Iterator(Iterable[_T], Generic[_T]):
    @abstractmethod
    def next(self) -> _T: ...

class Sequence(Sized, Iterable[_T], Generic[_T]):
    @abstractmethod
    def __contains__(self, x: object) -> bool: ...
    @overload
    @abstractmethod
    def __getitem__(self, i: int) -> _T: ...
    @overload
    @abstractmethod
    def __getitem__(self, s: slice) -> Sequence[_T]: ...
    @abstractmethod
    def index(self, x: Any) -> int: ...
    @abstractmethod
    def count(self, x: Any) -> int: ...

class AbstractSet(Sized, Iterable[_T], Generic[_T]):
    @abstractmethod
    def __contains__(self, x: object) -> bool: ...
    # TODO __le__, __lt__, __gt__, __ge__
    @abstractmethod
    def __and__(self, s: AbstractSet[_T]) -> AbstractSet[_T]: ...
    @abstractmethod
    def __or__(self, s: AbstractSet[_T]) -> AbstractSet[_T]: ...
    @abstractmethod
    def __sub__(self, s: AbstractSet[_T]) -> AbstractSet[_T]: ...
    @abstractmethod
    def __xor__(self, s: AbstractSet[_T]) -> AbstractSet[_T]: ...
    # TODO argument can be any container?
    @abstractmethod
    def isdisjoint(self, s: AbstractSet[_T]) -> bool: ...

class Mapping(Sized, Iterable[_KT], Generic[_KT, _VT]):
    @abstractmethod
    def __getitem__(self, k: _KT) -> _VT: ...
    @abstractmethod
    def __setitem__(self, k: _KT, v: _VT) -> None: ...
    @abstractmethod
    def __delitem__(self, v: _KT) -> None: ...
    @abstractmethod
    def __contains__(self, o: object) -> bool: ...

    @abstractmethod
    def clear(self) -> None: ...
    @abstractmethod
    def copy(self) -> Mapping[_KT, _VT]: ...
    @overload
    @abstractmethod
    def get(self, k: _KT) -> _VT: ...
    @overload
    @abstractmethod
    def get(self, k: _KT, default: _VT) -> _VT: ...
    @overload
    @abstractmethod
    def pop(self, k: _KT) -> _VT: ...
    @overload
    @abstractmethod
    def pop(self, k: _KT, default: _VT) -> _VT: ...
    @abstractmethod
    def popitem(self) -> Tuple[_KT, _VT]: ...
    @overload
    @abstractmethod
    def setdefault(self, k: _KT) -> _VT: ...
    @overload
    @abstractmethod
    def setdefault(self, k: _KT, default: _VT) -> _VT: ...

    # TODO keyword arguments
    @overload
    @abstractmethod
    def update(self, m: Mapping[_KT, _VT]) -> None: ...
    @overload
    @abstractmethod
    def update(self, m: Iterable[Tuple[_KT, _VT]]) -> None: ...

    @abstractmethod
    def keys(self) -> list[_KT]: ...
    @abstractmethod
    def values(self) -> list[_VT]: ...
    @abstractmethod
    def items(self) -> list[Tuple[_KT, _VT]]: ...
    @abstractmethod
    def iterkeys(self) -> Iterator[_KT]: ...
    @abstractmethod
    def itervalues(self) -> Iterator[_VT]: ...
    @abstractmethod
    def iteritems(self) -> Iterator[Tuple[_KT, _VT]]: ...

class IO(Iterable[AnyStr], Generic[AnyStr]):
    # TODO detach
    # TODO use abstract properties
    @property
    def mode(self) -> str: ...
    @property
    def name(self) -> str: ...
    @abstractmethod
    def close(self) -> None: ...
    @property
    def closed(self) -> bool: ...
    @abstractmethod
    def fileno(self) -> int: ...
    @abstractmethod
    def flush(self) -> None: ...
    @abstractmethod
    def isatty(self) -> bool: ...
    # TODO what if n is None?
    @abstractmethod
    def read(self, n: int = -1) -> AnyStr: ...
    @abstractmethod
    def readable(self) -> bool: ...
    @abstractmethod
    def readline(self, limit: int = -1) -> AnyStr: ...
    @abstractmethod
    def readlines(self, hint: int = -1) -> list[AnyStr]: ...
    @abstractmethod
    def seek(self, offset: int, whence: int = 0) -> int: ...
    @abstractmethod
    def seekable(self) -> bool: ...
    @abstractmethod
    def tell(self) -> int: ...
    # TODO None should not be compatible with int
    @abstractmethod
    def truncate(self, size: int = None) -> int: ...
    @abstractmethod
    def writable(self) -> bool: ...
    # TODO buffer objects
    @abstractmethod
    def write(self, s: AnyStr) -> int: ...
    @abstractmethod
    def writelines(self, lines: Iterable[AnyStr]) -> None: ...

    @abstractmethod
    def __iter__(self) -> Iterator[AnyStr]: ...
    @abstractmethod
    def __enter__(self) -> 'IO[AnyStr]': ...
    @abstractmethod
    def __exit__(self, type, value, traceback) -> bool: ...

class BinaryIO(IO[str]):
    # TODO readinto
    # TODO read1?
    # TODO peek?
    @overload
    @abstractmethod
    def write(self, s: str) -> int: ...
    @overload
    @abstractmethod
    def write(self, s: bytearray) -> int: ...

    @abstractmethod
    def __enter__(self) -> BinaryIO: ...

class TextIO(IO[unicode]):
    # TODO use abstractproperty
    @property
    def buffer(self) -> BinaryIO: ...
    @property
    def encoding(self) -> str: ...
    @property
    def errors(self) -> str: ...
    @property
    def line_buffering(self) -> bool: ...
    @property
    def newlines(self) -> Any: ... # None, str or tuple
    @abstractmethod
    def __enter__(self) -> TextIO: ...

class Match(Generic[AnyStr]):
    pos = 0
    endpos = 0
    lastindex = 0
    lastgroup = Undefined(AnyStr)
    string = Undefined(AnyStr)

    # The regular expression object whose match() or search() method produced
    # this match instance.
    re = Undefined('Pattern[AnyStr]')

    def expand(self, template: AnyStr) -> AnyStr: ...

    @overload
    def group(self, group1: int = 0) -> AnyStr: ...
    @overload
    def group(self, group1: str) -> AnyStr: ...
    @overload
    def group(self, group1: int, group2: int,
              *groups: int) -> Sequence[AnyStr]: ...
    @overload
    def group(self, group1: str, group2: str,
              *groups: str) -> Sequence[AnyStr]: ...

    def groups(self, default: AnyStr = None) -> Sequence[AnyStr]: ...
    def groupdict(self, default: AnyStr = None) -> dict[str, AnyStr]: ...
    def start(self, group: int = 0) -> int: ...
    def end(self, group: int = 0) -> int: ...
    def span(self, group: int = 0) -> Tuple[int, int]: ...

class Pattern(Generic[AnyStr]):
    flags = 0
    groupindex = 0
    groups = 0
    pattern = Undefined(AnyStr)

    def search(self, string: AnyStr, pos: int = 0,
               endpos: int = -1) -> Match[AnyStr]: ...
    def match(self, string: AnyStr, pos: int = 0,
              endpos: int = -1) -> Match[AnyStr]: ...
    def split(self, string: AnyStr, maxsplit: int = 0) -> list[AnyStr]: ...
    def findall(self, string: AnyStr, pos: int = 0,
                endpos: int = -1) -> list[AnyStr]: ...
    def finditer(self, string: AnyStr, pos: int = 0,
                 endpos: int = -1) -> Iterator[Match[AnyStr]]: ...

    @overload
    def sub(self, repl: AnyStr, string: AnyStr,
            count: int = 0) -> AnyStr: ...
    @overload
    def sub(self, repl: Callable[[Match[AnyStr]], AnyStr], string: AnyStr,
            count: int = 0) -> AnyStr: ...

    @overload
    def subn(self, repl: AnyStr, string: AnyStr,
             count: int = 0) -> Tuple[AnyStr, int]: ...
    @overload
    def subn(self, repl: Callable[[Match[AnyStr]], AnyStr], string: AnyStr,
             count: int = 0) -> Tuple[AnyStr, int]: ...
