# Stubs for email.policy (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Undefined, Any
import email._policybase

Policy = email._policybase.Policy
Compat32 = email._policybase.Compat32

class EmailPolicy(Policy):
    refold_source = Undefined(Any)
    header_factory = Undefined(Any)
    content_manager = Undefined(Any)
    def __init__(self, **kw): ...
    def header_max_count(self, name): ...
    def header_source_parse(self, sourcelines): ...
    def header_store_parse(self, name, value): ...
    def header_fetch_parse(self, name, value): ...
    def fold(self, name, value): ...
    def fold_binary(self, name, value): ...

default = Undefined(Any)
strict = Undefined(Any)
SMTP = Undefined(Any)
HTTP = Undefined(Any)
